const DIAGNOSTIC_CODES = [
    "none",
    "syntax-error",
    "doc-syntax-error",
    "type-not-found",
    "missing-return",
    "param-type-mismatch",
    "missing-parameter",
    "redundant-parameter",
    "unreachable-code",
    "unused",
    "unused-self",
    "undefined-global",
    "deprecated",
    "access-invisible",
    "discard-returns",
    "undefined-field",
    "local-const-reassign",
    "iter-variable-reassign",
    "duplicate-type",
    "redefined-local",
    "redefined-label",
    "code-style-check",
    "need-check-nil",
    "await-in-sync",
    "annotation-usage-error",
    "return-type-mismatch",
    "missing-return-value",
    "redundant-return-value",
    "undefined-doc-param",
    "duplicate-doc-field",
    "unknown-doc-tag",
    "missing-fields",
    "inject-field",
    "circle-doc-class",
    "incomplete-signature-doc",
    "missing-global-doc",
    "assign-type-mismatch",
    "duplicate-require",
    "non-literal-expressions-in-assert",
    "unbalanced-assignments",
    "unnecessary-assert",
    "unnecessary-if",
    "duplicate-set-field",
    "duplicate-index",
    "generic-constraint-mismatch",
    "cast-type-mismatch",
    "require-module-not-visible",
    "enum-value-mismatch",
    "preferred-local-alias",
    "read-only",
    "global-in-non-module",
    "attribute-param-type-mismatch",
    "attribute-missing-parameter",
    "attribute-redundant-parameter",
    "invert-if",
    "call-non-callable",
    "gmod-invalid-hook-name",
    "gmod-realm-misuse",
    "gmod-realm-misuse-risky",
    "gmod-unknown-net-message",
    "gmod-duplicate-system-registration",
];

const DIAGNOSTIC_SEVERITY_VALUES = [
    "error",
    "warning",
    "information",
    "hint",
];
const DIAGNOSTIC_STATE_CODES = DIAGNOSTIC_CODES.filter(
    (code) => code !== "none",
);
const DIAGNOSTIC_DEFAULT_SEVERITY = {
    "syntax-error": "error",
    "doc-syntax-error": "error",
    "unreachable-code": "hint",
    unused: "hint",
    "unused-self": "hint",
    "undefined-global": "error",
    deprecated: "hint",
    "local-const-reassign": "error",
    "annotation-usage-error": "error",
    "redefined-local": "hint",
    "duplicate-require": "hint",
    "iter-variable-reassign": "error",
    "preferred-local-alias": "hint",
    "gmod-realm-misuse-risky": "hint",
    "gmod-duplicate-system-registration": "hint",
};

const DIAGNOSTIC_DEFAULT_ENABLE = {
    "missing-return": false,
    "unused-self": false,
    "iter-variable-reassign": false,
    "duplicate-type": false,
    "code-style-check": false,
    "return-type-mismatch": false,
    "redundant-return-value": false,
    "unknown-doc-tag": false,
    "inject-field": false,
    "incomplete-signature-doc": false,
    "missing-global-doc": false,
    "unnecessary-if": false,
    "unnecessary-assert": false,
    "duplicate-set-field": false,
    "global-in-non-module": false,
    "call-non-callable": false,
    "invert-if": false,
    "non-literal-expressions-in-assert": false,
};

const HIDDEN_SETTINGS = new Set([
    "runtime.version",
    "doc.rstDefaultRole",
    "doc.rstPrimaryDomain",
    "diagnostics.disable",
]);

const EFFECTIVE_DEFAULTS = {
    "gmod.autoLoadAnnotations": true,
    "gmod.detectRealmFromFilename": true,
    "gmod.detectRealmFromCalls": true,
};

const DESCRIPTION_OVERRIDES = {
    "resource.paths":
        "File paths used for document link resolution (ctrl+click on string literals). Not used for module indexing.",
    "runtime.special":
        "Maps special function names to their semantic behavior (e.g., marks `require` as a module loader, `type` as a type-check function). Affects how the analyzer treats calls to these functions.",
    "diagnostics.enables":
        "Override the enabled/disabled state for individual diagnostic codes. 'Force Enable' adds the code to the enables list; 'Force Disable' adds it to the disable list. If a code is in both lists, disable takes precedence.",
    "diagnostics.globals":
        'Suppresses "undefined-global" diagnostics for these specific variable names. Use this for globals injected by the GMod runtime that the analyzer cannot detect automatically.',
    "diagnostics.globalsRegex":
        "Like `globals`, but uses regex patterns to match global variable names. Invalid regex patterns are silently ignored.",
    "completion.autoRequireSeparator":
        "The path separator used when generating require() paths in auto-import completions. Also used when rewriting require paths on file relocation.",
    "completion.postfix":
        "The trigger character for postfix code snippets.",
    "hover.customDetail":
        "Controls the verbosity level of hover documentation (1–255). Leave empty for the default level. Higher values show more detail.",
    "references.fuzzySearch":
        "When an exact symbol search finds no results, falls back to a broader member-key lookup. This is not true fuzzy matching.",
    "references.shortStringSearch":
        "Includes string literals in reference searches. String values up to a certain length are indexed as potential references.",
    "strict.docBaseConstMatchBaseType":
        "When enabled, literal constant types defined in `@alias` annotations can match their base primitive types (e.g., an integer alias can accept `number` values).",
    "strict.metaOverrideFileDefine":
        "When enabled, type definitions from meta files (like the GMod annotations) take precedence over definitions in local project files.",
    "strict.requireExportGlobal":
        "When enabled, library modules must use `---@export global` to make their symbols visible in auto-import. Tightens library isolation.",
    "strict.requirePath":
        "When enabled, require() path resolution is exact. When disabled, partial/fuzzy module resolution is allowed and require paths are rewritten on file rename.",
    "doc.privateName":
        "Field name patterns treated as private (e.g., `m_*` marks `obj.m_id` as private). Private fields can only be accessed within the defining class.",
    "semanticTokens.renderDocumentationMarkup":
        "When enabled, Markdown in documentation comments is rendered in hover popups and tooltips instead of shown as raw text.",
    "doc.syntax":
        "Documentation comment syntax style. Recommended to use `md` for markdown.",
    "gmod.plugins":
        "Enable plugin presets for this workspace, search them quickly, and adjust enabled-plugin priority without reordering the visible table.",
};

const LABEL_OVERRIDES = {
    "diagnostics.enables": "Diagnostic State Overrides",
    "gmod.plugins": "Enabled Plugin Presets",
};

const PATH_FIELD_KEYWORDS = [
    "library",
    "root",
    "path",
    "dir",
    "ignore",
    "resource",
    "package",
];

const FORMAT_CATEGORY_KEY = "format";
const FORMAT_PRESET_PATH = ["format", "preset"];
const FORMAT_CONFIG_PRECEDENCE_PATH = [
    "format",
    "configPrecedence",
];
const FORMAT_STYLE_OVERRIDES_PATH = ["format", "styleOverrides"];

const FORMAT_PRESET_VALUES = ["default", "cfc", "custom"];
const FORMAT_CONFIG_PRECEDENCE_VALUES = [
    "preferEditorconfig",
    "preferGluarc",
];
const FORMAT_LINE_SPACE_FIELDS = new Set([
    "line_space_after_if_statement",
    "line_space_after_do_statement",
    "line_space_after_while_statement",
    "line_space_after_repeat_statement",
    "line_space_after_for_statement",
    "line_space_after_local_or_assign_statement",
    "line_space_after_function_statement",
    "line_space_after_expression_statement",
    "line_space_after_comment",
    "line_space_around_block",
]);

const FORMAT_ENUM_FIELDS = {
    indent_style: ["tab", "space"],
    quote_style: ["none", "single", "double"],
    end_of_line: ["crlf", "lf", "cr", "auto", "unset"],
    table_separator_style: [
        "none",
        "comma",
        "semicolon",
        "only_kv_colon",
    ],
    trailing_table_separator: ["keep", "never", "always", "smart"],
    call_arg_parentheses: [
        "keep",
        "remove",
        "remove_table_only",
        "remove_string_only",
    ],
    space_before_function_call_single_arg: [
        "always",
        "only_string",
        "only_table",
        "none",
    ],
    align_continuous_assign_statement: ["true", "false", "always"],
    align_array_table: ["none", "always", "contain_curly"],
    align_chain_expr: ["none", "always", "only_call_stmt"],
    end_statement_with_semicolon: [
        "keep",
        "always",
        "same_line",
        "replace_with_newline",
        "never",
    ],
    space_around_concat_operator: ["none", "always", "no_space_asym"],
    space_around_assign_operator: ["none", "always", "no_space_asym"],
};

const FORMAT_INTEGER_FIELDS = new Set([
    "indent_size",
    "tab_width",
    "continuation_indent",
    "max_line_length",
    "align_continuous_line_space",
]);

const FORMAT_BOOLEAN_FIELDS = new Set([
    "detect_end_of_line",
    "insert_final_newline",
    "space_around_table_field_list",
    "space_before_attribute",
    "space_before_function_open_parenthesis",
    "space_before_function_call_open_parenthesis",
    "space_before_closure_open_parenthesis",
    "space_before_open_square_bracket",
    "space_inside_function_call_parentheses",
    "space_inside_function_param_list_parentheses",
    "space_inside_square_brackets",
    "space_around_table_append_operator",
    "ignore_spaces_inside_function_call",
    "space_after_comment_dash",
    "space_around_math_operator",
    "space_after_comma",
    "space_after_comma_in_for_statement",
    "space_around_logical_operator",
    "align_call_args",
    "align_function_params",
    "align_continuous_rect_table_field",
    "align_if_branch",
    "align_continuous_similar_call_args",
    "align_continuous_inline_comment",
    "never_indent_before_if_condition",
    "never_indent_comment_on_if_branch",
    "keep_indents_on_empty_lines",
    "allow_non_indented_comments",
    "break_all_list_when_line_exceed",
    "auto_collapse_lines",
    "break_before_braces",
    "ignore_space_after_colon",
    "remove_call_expression_list_finish_comma",
]);

const FORMAT_CFC_PRESET = {
    indent_style: 'space',
    indent_size: 4,
    tab_width: 4,
    max_line_length: 110,
    space_inside_function_call_parentheses: true,
    space_inside_function_param_list_parentheses: true,
    space_around_table_field_list: true,
    space_inside_square_brackets: false,
    space_after_comment_dash: true,
    end_statement_with_semicolon: 'replace_with_newline',
};

const FORMAT_ENGINE_DEFAULTS = {
    indent_style: "space",
    indent_size: 4,
    tab_width: 4,
    quote_style: "none",
    continuation_indent: 4,
    max_line_length: 120,
    end_of_line: "crlf",
    table_separator_style: "comma",
    trailing_table_separator: "keep",
    call_arg_parentheses: "keep",
    detect_end_of_line: true,
    insert_final_newline: true,
    space_around_table_field_list: true,
    space_before_attribute: true,
    space_before_function_open_parenthesis: false,
    space_before_function_call_open_parenthesis: false,
    space_before_closure_open_parenthesis: false,
    space_before_function_call_single_arg: "always",
    space_before_open_square_bracket: false,
    space_inside_function_call_parentheses: false,
    space_inside_function_param_list_parentheses: false,
    space_inside_square_brackets: false,
    space_around_table_append_operator: false,
    ignore_spaces_inside_function_call: false,
    space_before_inline_comment: 1,
    space_after_comment_dash: false,
    space_around_math_operator: true,
    space_after_comma: true,
    space_after_comma_in_for_statement: true,
    space_around_concat_operator: "always",
    space_around_logical_operator: true,
    space_around_assign_operator: "always",
    align_call_args: false,
    align_function_params: true,
    align_continuous_assign_statement: "true",
    align_continuous_rect_table_field: true,
    align_continuous_line_space: 2,
    align_if_branch: false,
    align_array_table: "always",
    align_continuous_similar_call_args: false,
    align_continuous_inline_comment: true,
    align_chain_expr: "none",
    never_indent_before_if_condition: false,
    never_indent_comment_on_if_branch: false,
    keep_indents_on_empty_lines: false,
    allow_non_indented_comments: false,
    line_space_after_if_statement: "keep",
    line_space_after_do_statement: "keep",
    line_space_after_while_statement: "keep",
    line_space_after_repeat_statement: "keep",
    line_space_after_for_statement: "keep",
    line_space_after_local_or_assign_statement: "keep",
    line_space_after_function_statement: "fixed(2)",
    line_space_after_expression_statement: "keep",
    line_space_after_comment: "keep",
    line_space_around_block: "fixed(1)",
    break_all_list_when_line_exceed: false,
    auto_collapse_lines: false,
    break_before_braces: false,
    ignore_space_after_colon: false,
    remove_call_expression_list_finish_comma: false,
    end_statement_with_semicolon: "keep",
};

const FORMAT_DESCRIPTIONS = {
    detect_end_of_line: "Auto-detect the most common newline sequence in the file and use it for formatting.",
    insert_final_newline: "Ensure the file ends with a newline character.",
    indent_style: "Use tab characters or spaces for indentation.",
    indent_size: "Number of spaces that represent one indentation level.",
    tab_width: "Visual display width of a tab character in spaces, used for alignment calculations. Does not change the indentation character.",
    quote_style: "Preferred quote style for string literals. 'none' preserves the original quoting style.",
    continuation_indent: "Number of extra spaces used for continuation line indentation when a line is wrapped.",
    max_line_length: "Column limit at which the formatter wraps items onto new lines. Set to 0 or 'unset' to disable line length enforcement.",
    end_of_line: "Line ending sequence to write: 'lf' (Unix), 'crlf' (Windows), 'cr', 'auto' (match file), or 'unset'.",
    table_separator_style: "Separator character between table fields: 'none', 'comma', 'semicolon', or 'only_kv_colon' (semicolons only for key-value pairs).",
    trailing_table_separator: "Policy for the separator after the last field in a table: 'keep', 'never', 'always', or 'smart' (adds trailing separator only for multiline tables).",
    call_arg_parentheses: "Handle parentheses around single string or table literal arguments: 'keep', 'remove', 'remove_table_only', or 'remove_string_only'.",
    space_around_table_field_list: "Add spaces inside table braces, e.g. { a = 1 } instead of {a = 1}.",
    space_before_attribute: "Add a space before Lua attribute annotations, e.g. `local x <const>`.",
    space_before_function_open_parenthesis: "Add a space before `(` in function declarations, e.g. `function foo ()`.",
    space_before_function_call_open_parenthesis: "Add a space before `(` in function calls, e.g. `print ('hello')`.",
    space_before_closure_open_parenthesis: "Add a space before `(` in anonymous function expressions, e.g. `function ()`.",
    space_before_function_call_single_arg: "Space handling before a single string or table literal argument passed without parentheses: 'always', 'only_string', 'only_table', or 'none'.",
    space_before_open_square_bracket: "Add a space before `[` in table index expressions, e.g. `t [key]`.",
    space_inside_function_call_parentheses: "Add spaces inside function call parentheses, e.g. `print( 'hello' )`.",
    space_inside_function_param_list_parentheses: "Add spaces inside function parameter list parentheses, e.g. `function foo( a, b )`.",
    space_inside_square_brackets: "Add spaces inside square bracket index expressions, e.g. `t[ 1 ]`.",
    space_around_table_append_operator: "Add spaces around table append-style expressions (`#t + 1` indexing).",
    ignore_spaces_inside_function_call: "Preserve existing spacing inside function call arguments instead of normalizing it.",
    space_before_inline_comment: "Number of spaces to enforce before inline comments (`--`), or 'keep' to preserve existing spacing.",
    space_after_comment_dash: "Ensure a single space exists after the comment dash prefix (`--`), e.g. `-- comment` instead of `--comment`.",
    space_around_math_operator: "Add spaces around math operators (`+`, `-`, `*`, `/`, `%`, `^`).",
    space_after_comma: "Add a space after commas in expressions and argument lists.",
    space_after_comma_in_for_statement: "Add a space after commas in `for` loop range and iterator expressions.",
    space_around_concat_operator: "Spaces around the concatenation operator (`..`). Use true/false, or: 'none' (no spaces), 'always' (spaces on both sides), 'no_space_asym' (space on left side only).",
    space_around_logical_operator: "Add spaces around logical operators (`and`, `or`, `not`).",
    space_around_assign_operator: "Spaces around assignment operators (`=`). Use true/false, or: 'none' (no spaces), 'always' (spaces on both sides), 'no_space_asym' (space on left side only, useful for aligning long assignments).",
    align_call_args: "Vertically align multi-line function call arguments to the opening parenthesis.",
    align_function_params: "Vertically align multi-line function declaration parameters to the opening parenthesis.",
    align_continuous_assign_statement: "Align consecutive assignment statements on their `=` sign. 'true' aligns within a block, 'always' aligns even across blank lines, 'false' disables.",
    align_continuous_rect_table_field: "Align key-value fields in rectangular table literals so that `=` signs line up vertically.",
    align_continuous_line_space: "Maximum number of blank lines allowed between consecutive statements before they are no longer considered part of the same aligned block.",
    align_if_branch: "Vertically align `if` / `elseif` / `else` condition keywords.",
    align_array_table: "Array table layout: 'none' keeps items inline, 'always' puts each item on its own line, 'contain_curly' uses multiline only when a nested table is present.",
    align_continuous_similar_call_args: "Align arguments across similar consecutive function calls so that matching argument positions line up vertically.",
    align_continuous_inline_comment: "Align the `--` of inline comments across consecutive lines so they form a vertical column.",
    align_chain_expr: "Align chained method/field expressions: 'none' disables, 'always' aligns all, 'only_call_stmt' aligns only standalone call statement chains.",
    never_indent_before_if_condition: "Do not add extra indentation to wrapped `if`/`elseif` condition expressions.",
    never_indent_comment_on_if_branch: "Do not indent a lone comment that appears inside an `if` branch body.",
    keep_indents_on_empty_lines: "Keep indentation whitespace on blank lines instead of stripping it.",
    allow_non_indented_comments: "Allow comments that start at column 0 to remain un-indented even when inside an indented block.",
    line_space_after_if_statement: "Blank lines to insert after an `if` statement block (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_do_statement: "Blank lines to insert after a `do` statement block (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_while_statement: "Blank lines to insert after a `while` statement block (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_repeat_statement: "Blank lines to insert after a `repeat` statement block (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_for_statement: "Blank lines to insert after a `for` statement block (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_local_or_assign_statement: "Blank lines to insert after local variable declarations or assignment statements (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_function_statement: "Blank lines to insert after function definition blocks (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_expression_statement: "Blank lines to insert after expression statements such as function calls (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_after_comment: "Blank lines to insert after standalone comment blocks (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    line_space_around_block: "Blank lines to insert before and after control-flow blocks such as `if`, `while`, and `for` (values: 'keep', 'fixed(n)', 'min(n)', 'max(n)').",
    break_all_list_when_line_exceed: "When a line exceeds `max_line_length`, break every item in the containing list onto its own line rather than only the overflowing item.",
    auto_collapse_lines: "Collapse short multi-statement blocks into a single line when they fit within `max_line_length`.",
    break_before_braces: "Place the opening `{` of a table constructor on a new line instead of at the end of the preceding line.",
    ignore_space_after_colon: "Do not normalize spacing after `:` in method call and definition syntax.",
    remove_call_expression_list_finish_comma: "Remove trailing commas that appear at the end of function call argument lists.",
    end_statement_with_semicolon: "Semicolon handling: 'keep' preserves existing, 'always' ensures every statement ends with one, 'same_line' adds between same-line statements, 'replace_with_newline' replaces semicolons with newlines, 'never' removes all."

};

const FORMAT_PREVIEWS = {
    indent_style: "-----[ space ]-----\nfunction example()\n    print('hello')\nend\n\n-----[ tab ]-----\nfunction example()\n\tprint('hello')\nend",
    indent_size: "-----[ 2 ]-----\nfunction example()\n  if true then\n    print('hi')\n  end\nend\n\n-----[ 4 ]-----\nfunction example()\n    if true then\n        print('hi')\n    end\nend",
    tab_width: "-----[ 2 ]-----\n-- Tab rendered as 2 spaces wide\nfunction example()\n\tprint('hello')   -- col 2\nend\n\n-----[ 4 ]-----\n-- Tab rendered as 4 spaces wide\nfunction example()\n    print('hello')  -- col 4\nend",
    quote_style: "-----[ single ]-----\nlocal x = 'string'\nlocal y = 'another'\n\n-----[ double ]-----\nlocal x = \"string\"\nlocal y = \"another\"\n\n-----[ none ]-----\n-- Original quotes preserved\nlocal x = 'single'\nlocal y = \"double\"",
    continuation_indent: "-----[ 0 (no extra indent) ]-----\nlocal result = very_long_function_name(\narg1,\narg2\n)\n\n-----[ 4 (extra indent) ]-----\nlocal result = very_long_function_name(\n    arg1,\n    arg2\n)",
    max_line_length: "-----[ 40 ]-----\n-- Long function call gets wrapped:\nsome_function(\n    first_argument,\n    second_argument\n)\n\n-----[ 120 ]-----\n-- Fits on one line:\nsome_function(first_argument, second_argument)",
    end_of_line: "-----[ lf ]-----\n-- Unix line endings (\\n)\n-- Standard for Linux/macOS\n\n-----[ crlf ]-----\n-- Windows line endings (\\r\\n)\n-- Standard for Windows\n\n-----[ auto ]-----\n-- Matches the most common\n-- sequence already in the file",
    table_separator_style: "-----[ comma ]-----\nlocal t = { 1, 2, 3 }\nlocal kv = { a = 1, b = 2 }\n\n-----[ semicolon ]-----\nlocal t = { 1; 2; 3 }\nlocal kv = { a = 1; b = 2 }\n\n-----[ only_kv_colon ]-----\nlocal t = { 1, 2, 3 }\nlocal kv = { a = 1; b = 2 }",
    trailing_table_separator: "-----[ keep ]-----\nlocal t = { 1, 2, }\nlocal u = { 1, 2 }\n\n-----[ never ]-----\nlocal t = { 1, 2 }\nlocal u = { 1, 2 }\n\n-----[ always ]-----\nlocal t = { 1, 2, }\nlocal u = { 1, 2, }\n\n-----[ smart ]-----\n-- Adds trailing sep for multiline only:\nlocal t = {\n    1,\n    2,\n}",
    call_arg_parentheses: "-----[ keep ]-----\nprint('hello')\nrequire('module')\n\n-----[ remove ]-----\nprint 'hello'\nrequire 'module'\n\n-----[ remove_string_only ]-----\nprint 'hello'\nfoo({1, 2})\n\n-----[ remove_table_only ]-----\nprint('hello')\nfoo {1, 2}",
    detect_end_of_line: "-----[ true ]-----\n-- Formatter auto-detects whether\n-- the file uses LF or CRLF and\n-- keeps that sequence.\n\n-----[ false ]-----\n-- Formatter applies the explicit\n-- end_of_line setting.",
    insert_final_newline: "-----[ true ]-----\nprint('hello')\n-- (newline inserted at end of file)\n\n-----[ false ]-----\nprint('hello')\n-- (no trailing newline)",
    space_around_table_field_list: "-----[ true ]-----\nlocal t = { a = 1, b = 2 }\nlocal u = { 'x', 'y', 'z' }\n\n-----[ false ]-----\nlocal t = {a = 1, b = 2}\nlocal u = {'x', 'y', 'z'}",
    space_before_attribute: "-----[ true ]-----\nlocal x <const> = 1\nlocal y <close> = io.open('f')\n\n-----[ false ]-----\nlocal x<const> = 1\nlocal y<close> = io.open('f')",
    space_before_function_open_parenthesis: "-----[ true ]-----\nfunction foo ()\n    return 1\nend\n\nfunction bar (x, y)\n    return x + y\nend\n\n-----[ false ]-----\nfunction foo()\n    return 1\nend",
    space_before_function_call_open_parenthesis: "-----[ true ]-----\nprint ('hello')\nmath.max (1, 2)\nENT:SetModel ('models/error.mdl')\n\n-----[ false ]-----\nprint('hello')\nmath.max(1, 2)\nENT:SetModel('models/error.mdl')",
    space_before_closure_open_parenthesis: "-----[ true ]-----\nlocal f = function ()\n    return 1\nend\nhook.Add('Think', 'id', function ()\nend)\n\n-----[ false ]-----\nlocal f = function()\n    return 1\nend",
    space_before_function_call_single_arg: "-----[ always ]-----\nprint 'hello'\nrequire 'module'\nfoo {1, 2, 3}\n\n-----[ only_string ]-----\nprint 'hello'\nrequire 'module'\nfoo({1, 2, 3})\n\n-----[ only_table ]-----\nprint('hello')\nrequire('module')\nfoo {1, 2, 3}\n\n-----[ none ]-----\nprint'hello'\nfoo{1, 2}",
    space_before_open_square_bracket: "-----[ true ]-----\nlocal x = t [1]\nlocal y = t ['key']\nt [i] = value\n\n-----[ false ]-----\nlocal x = t[1]\nlocal y = t['key']",
    space_inside_function_call_parentheses: "-----[ true ]-----\nprint( 'hello' )\nmath.max( 1, 2 )\nENT:SetPos( Vector(0,0,0) )\n\n-----[ false ]-----\nprint('hello')\nmath.max(1, 2)",
    space_inside_function_param_list_parentheses: "-----[ true ]-----\nfunction foo( a, b )\n    return a + b\nend\n\nlocal f = function( x, y )\n    return x * y\nend\n\n-----[ false ]-----\nfunction foo(a, b)\n    return a + b\nend",
    space_inside_square_brackets: "-----[ true ]-----\nlocal x = t[ 1 ]\nlocal y = t[ 'key' ]\nt[ i ] = value\n\n-----[ false ]-----\nlocal x = t[1]\nlocal y = t['key']",
    space_around_table_append_operator: "-----[ true ]-----\nt[ #t + 1 ] = 'value'\n\n-----[ false ]-----\nt[#t+1] = 'value'",
    ignore_spaces_inside_function_call: "-----[ true ]-----\n-- Spacing inside calls is preserved\ncall(  a,  b  )\nprint(   'hello'   )\n\n-----[ false ]-----\n-- Spacing is normalized\ncall(a, b)\nprint('hello')",
    space_before_inline_comment: "-----[ 2 ]-----\nlocal a = 1  -- comment\nlocal bb = 2  -- comment\nlocal ccc = 3  -- comment\n\n-----[ keep ]-----\n-- Existing spacing is preserved\nlocal a = 1 -- comment\nlocal bb = 2    -- comment",
    space_after_comment_dash: "-----[ true ]-----\n-- This is a comment\n-- Another comment\nlocal x = 1 -- inline comment\n\n-----[ false ]-----\n--This is a comment\n--Another comment\nlocal x = 1 --inline comment",
    space_around_math_operator: "-----[ true ]-----\nlocal x = 1 + 2 * 3\nlocal y = a - b / c\nlocal z = x ^ 2 % 10\n\n-----[ false ]-----\nlocal x = 1+2*3\nlocal y = a-b/c\nlocal z = x^2%10",
    space_after_comma: "-----[ true ]-----\nlocal t = {1, 2, 3}\nfoo(a, b, c)\nlocal a, b, c = 1, 2, 3\n\n-----[ false ]-----\nlocal t = {1,2,3}\nfoo(a,b,c)\nlocal a,b,c = 1,2,3",
    space_after_comma_in_for_statement: "-----[ true ]-----\nfor i = 1, 10, 2 do\n    print(i)\nend\n\nfor k, v in pairs(t) do\n    print(k, v)\nend\n\n-----[ false ]-----\nfor i = 1,10,2 do\n    print(i)\nend",
    space_around_concat_operator: "-----[ true (or 'always') ]-----\nlocal s = 'hello' .. ' ' .. 'world'\nlocal path = dir .. '/' .. file\n\n-----[ false (or 'none') ]-----\nlocal s = 'hello'..' '..'world'\nlocal path = dir..'/'..' '..file\n\n-----[ no_space_asym ]-----\n-- Space on left side only:\nlocal s = 'hello' ..' '..'world'",
    space_around_logical_operator: "-----[ true ]-----\nif a and b or c then\n    return true\nend\nlocal ok = x and y or z\n\n-----[ false ]-----\nif a and b or c then\n    return true\nend",
    space_around_assign_operator: "-----[ true (or 'always') ]-----\nlocal a = 1\nlocal b = 'hello'\nx = x + 1\n\n-----[ false (or 'none') ]-----\nlocal a=1\nlocal b='hello'\n\n-----[ no_space_asym ]-----\n-- Space on left but not right:\nlocal a =1\nlocal b ='hello'",
    align_call_args: "-----[ true ]-----\nmy_func(first_arg,\n        second_arg,\n        third_arg)\n\n-----[ false ]-----\nmy_func(first_arg,\n    second_arg,\n    third_arg)",
    align_function_params: "-----[ true ]-----\nfunction func(first_param,\n              second_param,\n              third_param)\nend\n\n-----[ false ]-----\nfunction func(first_param,\n    second_param,\n    third_param)\nend",
    align_continuous_assign_statement: "-----[ true ]-----\n-- Aligned within block, stops at blank lines:\nlocal x      = 1\nlocal name   = 'hello'\nlocal longer = true\n\n-----[ always ]-----\n-- Aligned even across blank lines:\nlocal x      = 1\n\nlocal name   = 'hello'\nlocal longer = true\n\n-----[ false ]-----\nlocal x = 1\nlocal name = 'hello'\nlocal longer = true",
    align_continuous_rect_table_field: "-----[ true ]-----\nlocal cfg = {\n    name    = 'server',\n    port    = 8080,\n    verbose = true,\n}\n\n-----[ false ]-----\nlocal cfg = {\n    name = 'server',\n    port = 8080,\n    verbose = true,\n}",
    align_continuous_line_space: "-----[ 0 ]-----\n-- Statements must be adjacent to align\nlocal a = 1\nlocal b = 2\n-- blank line below breaks alignment:\n\nlocal c = 3\n\n-----[ 2 ]-----\n-- Up to 2 blank lines still aligns:\nlocal a = 1\n\n\nlocal b = 2\n-- still part of aligned block",
    align_if_branch: "-----[ true ]-----\nif     a == 1 then\n    foo()\nelseif b == 2 then\n    bar()\nend\n\n-----[ false ]-----\nif a == 1 then\n    foo()\nelseif b == 2 then\n    bar()\nend",
    align_array_table: "-----[ always ]-----\nlocal t = {\n    1,\n    2,\n    3,\n}\n\n-----[ none ]-----\nlocal t = { 1, 2, 3 }\n\n-----[ contain_curly ]-----\n-- Multiline only when nested table present:\nlocal a = { 1, 2, 3 }\nlocal b = {\n    { 1, 2 },\n    { 3, 4 },\n}",
    align_continuous_similar_call_args: "-----[ true ]-----\nfoo(a,      b)\nfoo(longer, d)\nfoo(x,      y)\n\n-----[ false ]-----\nfoo(a, b)\nfoo(longer, d)\nfoo(x, y)",
    align_continuous_inline_comment: "-----[ true ]-----\nlocal a = 1     -- first\nlocal bbb = 2   -- second\nlocal cc = 3    -- third\n\n-----[ false ]-----\nlocal a = 1 -- first\nlocal bbb = 2 -- second\nlocal cc = 3 -- third",
    align_chain_expr: "-----[ always ]-----\nresult = builder\n    :withName('foo')\n    :withValue(42)\n    :build()\n\n-----[ only_call_stmt ]-----\n-- Only standalone call statements:\nbuilder\n    :withName('foo')\n    :build()\n-- Inline usage is not aligned:\nlocal x = obj:method():chain()\n\n-----[ none ]-----\nresult = builder:withName('foo'):withValue(42):build()",
    never_indent_before_if_condition: "-----[ true ]-----\nif a\nand b\nand c then\n    print('yes')\nend\n\n-----[ false ]-----\nif a\n    and b\n    and c then\n    print('yes')\nend",
    never_indent_comment_on_if_branch: "-----[ true ]-----\nif true then\n-- comment stays at branch indent\nend\n\n-----[ false ]-----\nif true then\n    -- comment is indented\nend",
    keep_indents_on_empty_lines: "-----[ true ]-----\nfunction foo()\n    print(1)\n    \n    print(2)\nend\n\n-----[ false ]-----\nfunction foo()\n    print(1)\n-- (empty line has no indent whitespace)\n    print(2)\nend",
    allow_non_indented_comments: "-----[ true ]-----\nfunction foo()\n-- this comment stays at col 0\n    print(1)\nend\n\n-----[ false ]-----\nfunction foo()\n    -- comment is indented to match block\n    print(1)\nend",
    line_space_after_if_statement: "-----[ fixed(1) ]-----\nif true then\n    return\nend\n\nlocal x = 1\n\n-----[ keep ]-----\n-- Existing blank lines are preserved\nif true then\n    return\nend\nlocal x = 1",
    line_space_after_do_statement: "-----[ fixed(1) ]-----\ndo\n    local x = 1\nend\n\nprint(x)\n\n-----[ keep ]-----\ndo\n    local x = 1\nend\nprint(x)",
    line_space_after_while_statement: "-----[ fixed(1) ]-----\nwhile true do\n    break\nend\n\nlocal x = 1\n\n-----[ keep ]-----\nwhile true do\n    break\nend\nlocal x = 1",
    line_space_after_repeat_statement: "-----[ fixed(1) ]-----\nrepeat\n    x = x + 1\nuntil x > 10\n\nprint(x)\n\n-----[ keep ]-----\nrepeat\n    x = x + 1\nuntil x > 10\nprint(x)",
    line_space_after_for_statement: "-----[ fixed(1) ]-----\nfor i = 1, 10 do\n    print(i)\nend\n\nlocal x = 1\n\n-----[ keep ]-----\nfor i = 1, 10 do\n    print(i)\nend\nlocal x = 1",
    line_space_after_local_or_assign_statement: "-----[ fixed(1) ]-----\nlocal x = 1\nlocal y = 2\n\nprint(x + y)\n\n-----[ keep ]-----\nlocal x = 1\nlocal y = 2\nprint(x + y)",
    line_space_after_function_statement: "-----[ fixed(1) ]-----\nfunction foo()\nend\n\nfunction bar()\nend\n\n-----[ keep ]-----\nfunction foo()\nend\nfunction bar()\nend",
    line_space_after_expression_statement: "-----[ fixed(1) ]-----\nfoo()\n\nbar()\n\n-----[ keep ]-----\nfoo()\nbar()",
    line_space_after_comment: "-----[ fixed(1) ]-----\n-- Section header\n\nlocal x = 1\n\n-----[ keep ]-----\n-- Section header\nlocal x = 1",
    line_space_around_block: "-----[ fixed(1) ]-----\nlocal x = 1\n\nif true then\n    print(x)\nend\n\nlocal y = 2\n\n-----[ keep ]-----\nlocal x = 1\nif true then\n    print(x)\nend\nlocal y = 2",
    break_all_list_when_line_exceed: "-----[ true ]-----\n-- When ANY arg overflows the limit,\n-- ALL args move to separate lines:\nfunction f(\n    very_long_arg_name_one,\n    very_long_arg_name_two\n)\n\n-----[ false ]-----\n-- Only overflowing items wrap:\nfunction f(short,\n    very_long_arg_name_two)",
    auto_collapse_lines: "-----[ true ]-----\nfunction foo() return 1 end\nif true then return end\n\n-----[ false ]-----\nfunction foo()\n    return 1\nend\nif true then\n    return\nend",
    break_before_braces: "-----[ true ]-----\nlocal t =\n{\n    1, 2, 3\n}\n\n-----[ false ]-----\nlocal t = {\n    1, 2, 3\n}",
    ignore_space_after_colon: "-----[ true ]-----\nfunction obj:  method()\n    return self\nend -- extra spaces kept\n\n-----[ false ]-----\nfunction obj:method()\n    return self\nend -- normalized",
    remove_call_expression_list_finish_comma: "-----[ true ]-----\n-- Trailing comma removed:\ncall(1, 2)\nfoo('a', 'b')\n\n-----[ false ]-----\n-- Trailing comma kept as-is:\ncall(1, 2,)\nfoo('a', 'b',)",
    end_statement_with_semicolon: "-----[ keep ]-----\n-- Semicolons preserved as-is\nlocal a = 1;\nlocal b = 2\n\n-----[ always ]-----\nlocal a = 1;\nlocal b = 2;\nprint(a);\n\n-----[ same_line ]-----\n-- Separates same-line stmts with ;\nlocal a = 1; local b = 2\n\n-----[ replace_with_newline ]-----\n-- Semicolons become newlines\nlocal a = 1\nlocal b = 2\n\n-----[ never ]-----\n-- All semicolons removed\nlocal a = 1\nlocal b = 2\nprint(a)",
};

const FORMAT_GROUPS = [
    {
        title: "Basic",
        keys: [
            "indent_style",
            "indent_size",
            "tab_width",
            "quote_style",
            "continuation_indent",
            "max_line_length",
            "end_of_line",
            "table_separator_style",
            "trailing_table_separator",
            "call_arg_parentheses",
            "detect_end_of_line",
            "insert_final_newline",
        ],
    },
    {
        title: "Spacing",
        keys: [
            "space_around_table_field_list",
            "space_before_attribute",
            "space_before_function_open_parenthesis",
            "space_before_function_call_open_parenthesis",
            "space_before_closure_open_parenthesis",
            "space_before_function_call_single_arg",
            "space_before_open_square_bracket",
            "space_inside_function_call_parentheses",
            "space_inside_function_param_list_parentheses",
            "space_inside_square_brackets",
            "space_around_table_append_operator",
            "ignore_spaces_inside_function_call",
            "space_before_inline_comment",
            "space_after_comment_dash",
        ],
    },
    {
        title: "Operators",
        keys: [
            "space_around_math_operator",
            "space_after_comma",
            "space_after_comma_in_for_statement",
            "space_around_concat_operator",
            "space_around_logical_operator",
            "space_around_assign_operator",
        ],
    },
    {
        title: "Alignment",
        keys: [
            "align_call_args",
            "align_function_params",
            "align_continuous_assign_statement",
            "align_continuous_rect_table_field",
            "align_continuous_line_space",
            "align_if_branch",
            "align_array_table",
            "align_continuous_similar_call_args",
            "align_continuous_inline_comment",
            "align_chain_expr",
        ],
    },
    {
        title: "Indentation",
        keys: [
            "never_indent_before_if_condition",
            "never_indent_comment_on_if_branch",
            "keep_indents_on_empty_lines",
            "allow_non_indented_comments",
        ],
    },
    {
        title: "Line Spacing",
        keys: [
            "line_space_after_if_statement",
            "line_space_after_do_statement",
            "line_space_after_while_statement",
            "line_space_after_repeat_statement",
            "line_space_after_for_statement",
            "line_space_after_local_or_assign_statement",
            "line_space_after_function_statement",
            "line_space_after_expression_statement",
            "line_space_after_comment",
            "line_space_around_block",
        ],
    },
    {
        title: "Line Breaks",
        keys: [
            "break_all_list_when_line_exceed",
            "auto_collapse_lines",
            "break_before_braces",
        ],
    },
    {
        title: "Preferences",
        keys: [
            "ignore_space_after_colon",
            "remove_call_expression_list_finish_comma",
            "end_statement_with_semicolon",
        ],
    },
];

export {
    DIAGNOSTIC_CODES,
    DIAGNOSTIC_SEVERITY_VALUES,
    DIAGNOSTIC_STATE_CODES,
    DIAGNOSTIC_DEFAULT_SEVERITY,
    DIAGNOSTIC_DEFAULT_ENABLE,
    EFFECTIVE_DEFAULTS,
    HIDDEN_SETTINGS,
    DESCRIPTION_OVERRIDES,
    LABEL_OVERRIDES,
    PATH_FIELD_KEYWORDS,
    FORMAT_CATEGORY_KEY,
    FORMAT_PRESET_PATH,
    FORMAT_CONFIG_PRECEDENCE_PATH,
    FORMAT_STYLE_OVERRIDES_PATH,
    FORMAT_PRESET_VALUES,
    FORMAT_CONFIG_PRECEDENCE_VALUES,
    FORMAT_LINE_SPACE_FIELDS,
    FORMAT_ENUM_FIELDS,
    FORMAT_INTEGER_FIELDS,
    FORMAT_BOOLEAN_FIELDS,
    FORMAT_CFC_PRESET,
    FORMAT_ENGINE_DEFAULTS,
    FORMAT_DESCRIPTIONS,
    FORMAT_PREVIEWS,
    FORMAT_GROUPS,
};
